name: "Manual build and Scan"
on: workflow_dispatch

jobs:
  build:
    name: Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout https://github.com/${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: aikido-scanner
        # You may pin to the exact commit or the version.
        # uses: gusfune/aikido-scanner@26a22e15a650c9077d7a9f46cf4079110101a1c4
        uses: gusfune/aikido-scanner@1.0.19
        with:
          api_key: ${{secrets.API_KEY}}
